---
# role: di_netboot
# file: tasks/unset.yml
#
# Tasks to unset di_netboot, i.e. remove the tree of files.
# Each task should be clearly named, with no inventory variable in the name.

- name: "remove tftp root directory"
  file:
    path: "{{ di_netboot__path }}"
    state: absent
